export const COLORS = {
  LIGHT_BLUE: '#F3F7FA',
  BLUE: '#2196F3',
  BLACK: '#4A4A4A',
  WHITE: '#FFFFFF',
  LIGHT_GRAY: '#DFE5EC',
  CHECKBOX_GRAY: '#9ABBCE',
  CHECKBOX_BLUE: '#2196F3',
  CHECKBOX_LIGHT_BLUE: '#F1FCFF',
  CHECKBOX_SHADOW_BLUE: '#89C7F9',
  TEXT_GRAY: '#A0B0B9',
}
